name: music_player
description: A modern music player built with Flutter and Clean Architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  palette_generator: ^0.3.3+6
  flutter_bloc: ^8.1.6
  just_audio: ^0.9.40  # Para reproducción de audio
  file_picker: ^8.1.2  # Para seleccionar archivos locales

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/recently_played.jpg
    - assets/images/most_played.jpg
    - assets/images/playlist_01.jpg
    - assets/images/playlist_02.jpg
    - assets/images/playlist_03.jpg
    - assets/images/track_placeholder.jpg
    - assets/images/sunflower.jpg
    - assets/images/blinding_lights.jpg
    - assets/images/shape_of_you.jpg