name: reproductor
description: "Reproductor de música moderno con Flutter y Clean Architecture"

# Evita la publicación accidental a pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Paquetes esenciales
  flutter_bloc: ^8.1.3        # Para manejo de estado con BLoC
  equatable: ^2.0.5           # Para comparación de objetos
  just_audio: ^0.9.34         # Para reproducción de audio
  audio_service: ^0.18.9      # Para reproducción en segundo plano
  path_provider: ^2.0.15      # Para acceder a rutas del sistema
  rxdart: ^0.27.7
             # Para manejo de streams reactivos
  meta: ^1.9.1                # Para anotaciones
  uuid: ^3.0.7                # Para generación de IDs únicos

  # UI y diseño
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7         # Para manejo de SVG
  cached_network_image: ^3.3.0 # Para caché de imágenes
  shimmer: ^3.0.0             # Para efectos de carga
  percent_indicator: ^4.2.2   # Para barras de progreso circulares

  # Manejo de permisos
  permission_handler: ^10.4.0

  # Para manejo de metadata de archivos de audio
  flutter_media_metadata: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0       # Para buenas prácticas de código
  bloc_test: ^9.1.4           # Para testing de BLoCs
  mockito: ^5.4.2             # Para mocking en tests

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700